name: Lint

on:
  workflow_call:

permissions: read-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    container: golangci/golangci-lint:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Go 1.18.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run go mod tidy and save output
        run: |
          echo "GO_MOD_TIDY_OUTPUT=$(go mod tidy)" >> $GITHUB_ENV
      - name: Check for go mod tidy unknown revisions
        if: contains(['unknown revision'],env.GO_MOD_TIDY_OUTPUT)
        run: |
          exit 1
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Set up Go 1.18.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Lint
        run: make lint-copyright
